export const mockData = {
  user: {
    id: '1',
    nim: '1234567890',
    nama: 'John Doe',
    email: 'john@student.ac.id',
    prodi: 'Teknik Informatika',
    angkatan: 2022,
    semester: 5,
    noHp: '081234567890',
    alamat: 'Jl. Contoh No. 123, Kota Contoh',
    foto: null,
  },
  
  jadwalHariIni: [
    {
      id: '1',
      kode: 'PW2',
      nama: 'Pemrograman Web 2',
      waktu: '08:00 - 09:40',
      ruangan: 'R.301',
      dosen: 'Dr. Ahmad',
      status: 'sedang_berjalan',
    },
    {
      id: '2',
      kode: 'BD',
      nama: 'Basis Data',
      waktu: '10:00 - 11:40',
      ruangan: 'R.302',
      dosen: 'Dr. Budi',
      status: 'akan_datang',
    },
    {
      id: '3',
      kode: 'PBO',
      nama: 'Pemrograman Berorientasi Objek',
      waktu: '13:00 - 14:40',
      ruangan: 'Lab.303',
      dosen: 'Dr. Citra',
      status: 'akan_datang',
    },
  ],
  
  tugasMendatang: [
    {
      id: '1',
      judul: 'Tugas 3 - React Native',
      mataKuliah: 'Pemrograman Web 2',
      deadline: '2024-12-20',
      status: 'belum',
      prioritas: 'tinggi',
    },
    {
      id: '2',
      judul: 'Quiz Basis Data',
      mataKuliah: 'Basis Data',
      deadline: '2024-12-18',
      status: 'dikerjakan',
      prioritas: 'sedang',
    },
    {
      id: '3',
      judul: 'Laporan PBO',
      mataKuliah: 'Pemrograman Berorientasi Objek',
      deadline: '2024-12-22',
      status: 'belum',
      prioritas: 'rendah',
    },
    {
      id: '4',
      judul: 'Presentasi Jaringan',
      mataKuliah: 'Jaringan Komputer',
      deadline: '2024-12-15',
      status: 'selesai',
      prioritas: 'tinggi',
    },
  ],
  
  khsData: [
    {
      id: '1',
      semester: 1,
      kode: 'MTK1',
      nama: 'Matematika Dasar 1',
      sks: 3,
      nilai: 85,
      grade: 'A',
    },
    {
      id: '2',
      semester: 1,
      kode: 'FIS1',
      nama: 'Fisika Dasar 1',
      sks: 3,
      nilai: 78,
      grade: 'B',
    },
    {
      id: '3',
      semester: 2,
      kode: 'MTK2',
      nama: 'Matematika Dasar 2',
      sks: 3,
      nilai: 82,
      grade: 'A',
    },
    {
      id: '4',
      semester: 2,
      kode: 'ALPRO',
      nama: 'Algoritma Pemrograman',
      sks: 3,
      nilai: 90,
      grade: 'A',
    },
    {
      id: '5',
      semester: 3,
      kode: 'STRUKDAT',
      nama: 'Struktur Data',
      sks: 3,
      nilai: 88,
      grade: 'A',
    },
    {
      id: '6',
      semester: 3,
      kode: 'OOP',
      nama: 'Pemrograman Berorientasi Objek',
      sks: 3,
      nilai: 85,
      grade: 'A',
    },
    {
      id: '7',
      semester: 4,
      kode: 'BD',
      nama: 'Basis Data',
      sks: 3,
      nilai: 87,
      grade: 'A',
    },
    {
      id: '8',
      semester: 4,
      kode: 'JARKOM',
      nama: 'Jaringan Komputer',
      sks: 3,
      nilai: 80,
      grade: 'B',
    },
    {
      id: '9',
      semester: 5,
      kode: 'PW2',
      nama: 'Pemrograman Web 2',
      sks: 3,
      nilai: 92,
      grade: 'A',
    },
    {
      id: '10',
      semester: 5,
      kode: 'ML',
      nama: 'Machine Learning',
      sks: 3,
      nilai: 89,
      grade: 'A',
    },
  ],
  
  notifikasi: [
    {
      id: '1',
      judul: 'Tugas Baru',
      pesan: 'Matematika Diskrit - Tugas 3 telah ditambahkan',
      waktu: '2 jam lalu',
      tipe: 'tugas',
      dibaca: false,
    },
    {
      id: '2',
      judul: 'Pesan Dosen',
      pesan: 'Bapak Ahmad mengirim pesan baru',
      waktu: '5 jam lalu',
      tipe: 'pesan',
      dibaca: false,
    },
    {
      id: '3',
      judul: 'Reminder Jadwal',
      pesan: 'Kuliah PW2 besok jam 08:00 di R.301',
      waktu: '1 hari lalu',
      tipe: 'jadwal',
      dibaca: true,
    },
    {
      id: '4',
      judul: 'Pengumuman',
      pesan: 'Libur akhir semester mulai 25 Desember',
      waktu: '2 hari lalu',
      tipe: 'pengumuman',
      dibaca: true,
    },
  ],
  
  mataKuliah: [
    {
      id: '1',
      kode: 'PW2',
      nama: 'Pemrograman Web 2',
      sks: 3,
      semester: 5,
      dosen: 'Dr. Ahmad',
      ruangan: 'R.301',
      jadwal: 'Senin, 08:00-09:40',
      nilai: 92,
    },
    {
      id: '2',
      kode: 'BD',
      nama: 'Basis Data',
      sks: 3,
      semester: 5,
      dosen: 'Dr. Budi',
      ruangan: 'R.302',
      jadwal: 'Selasa, 10:00-11:40',
      nilai: 87,
    },
    {
      id: '3',
      kode: 'PBO',
      nama: 'Pemrograman Berorientasi Objek',
      sks: 3,
      semester: 5,
      dosen: 'Dr. Citra',
      ruangan: 'Lab.303',
      jadwal: 'Rabu, 13:00-14:40',
      nilai: 85,
    },
    {
      id: '4',
      kode: 'JARKOM',
      nama: 'Jaringan Komputer',
      sks: 3,
      semester: 5,
      dosen: 'Dr. Dedi',
      ruangan: 'Lab.304',
      jadwal: 'Kamis, 08:00-09:40',
      nilai: 80,
    },
    {
      id: '5',
      kode: 'ML',
      nama: 'Machine Learning',
      sks: 3,
      semester: 5,
      dosen: 'Dr. Eka',
      ruangan: 'R.305',
      jadwal: 'Jumat, 10:00-11:40',
      nilai: 89,
    },
  ],
};

export default mockData;